browser=chrome
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username=Admin
password=admin123
implicitWait=13
explicitWait=13
expectedPageTitle=OrangeHRM
expectedUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login